markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "古文故事"
markdown: rdiscount

author: "古文故事"
atom-baseurl: "http://guwengushi.github.com"
disqus: "古文故事"

navigations:
  - title: 所有文章
    class: fa fa-list-ul
    href: /archive.html
  - title: 分类
    class: fa fa-tags
    href: /tags.html
  - title: 关于
    class: fa fa-user
    href: /about.html
  - title: 相册
    class: fa fa-film
    href: https://www.instagram.com/guwengushi/
  - title: 订阅
    class: fa fa-rss
    href: /atom.xml

