markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "hanly jiang"
markdown: rdiscount

author: "hanlyjiang"
atom-baseurl: "http://hanlyjiang.github.io"
disqus: "hanlyjiang"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.instagram.com/hanlyjiang/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
    
    
comments :
    provider : disqus
    disqus :
      short_name : hanlyjiang
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
